version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: books-api
    image: postgres
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/books-api
    volumes:
      - books-api:/var/lib/postgresql/data

volumes:
  books-api: